"""
AI Analytics Client for institutional validation.
Motto: "Intelligence-Driven, Infrastructure-Hardened Execution."

This client calls the Gemma-powered AI service to get a 'Second Opinion' 
on signals generated by the 7-Strategy engine.
"""
import httpx
import logging
import os
from typing import Dict, Any, Optional
from dotenv import load_dotenv

load_dotenv()

class AIValidationClient:
    def __init__(self, base_url: str = None):
        self.base_url = base_url or os.getenv("AI_SERVICE_URL", "http://localhost:7003")
        self.logger = logging.getLogger("AIValidationClient")

    async def validate_signal(self, symbol: str, direction: str, context: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """
        Calls the AI Service to analyze the current market context for a symbol.
        Returns the structured analysis and final decision.
        """
        payload = {
            "symbol": symbol,
            "context": context,
            "debug": False
        }
        
        async with httpx.AsyncClient(timeout=180.0) as client:
            try:
                resp = await client.post(f"{self.base_url}/analyze", json=payload)
                if resp.status_code == 200:
                    result = resp.json()
                    if result["status"] == "success":
                        analysis = dict(result["data"]["structured"])
                        # We only approve if the AI's categorical decision matches the signal direction
                        ai_decision = analysis.get("decision", "HOLD").upper()
                        
                        # Institutional Rule: AI must confirm the direction (BUY/BUY or SELL/SELL)
                        sig_dir = "BUY" if direction.upper() in ["BUY", "LONG"] else "SELL"

                        analysis["approved"] = (ai_decision == sig_dir)
                        if analysis["approved"]:
                            self.logger.info(f"AI CONFIRMED {sig_dir} for {symbol} (Conviction: {analysis.get('conviction')})")
                        else:
                            self.logger.warning(f"AI REJECTED {sig_dir} for {symbol} (Decision: {ai_decision})")
                        return analysis
            except Exception as e:
                self.logger.error(f"Error calling AI Service for {symbol}: {e}")
                return None
        return None
